### ISSUE TITLE
Nothing works :)

### ISSUE THREAD

**Issue by SrTobi** [phiresky/neural-network-demo#3]
## 1. typings.json

When I try to install typings with `typings install` inside of `lib` I get the following output:

```
/lib> typings install
└── (No dependencies)
```

I was able to resolve the problem by changing `typings.json`:

```
{
  "ambientDependencies": {
      ...
  }
}
```

to

```
{
  "globalDependencies": {
      ...
  }
}
```

This gives

```
/lib> typings install
typings WARN deprecated 9/30/2016: "registry:dt/highcharts#4.1.9+20160316155526" is deprecated (updated, replaced or removed)
typings WARN deprecated 6/19/2016: "registry:dt/bootstrap#3.3.5+20160316155526" is deprecated (updated, replaced or removed)
typings WARN deprecated 9/29/2016: "registry:dt/jquery#2.0.0+20160303223636" is deprecated (updated, replaced or removed)
typings WARN deprecated 10/8/2016: "registry:dt/react#0.14.0+20160412154040" is deprecated (updated, replaced or removed)
├── bootstrap (global)
├── highcharts (global)
├── highcharts/highstock (global)
├── jquery (global)
├── jquery-handsontable (global)
├── react (global)
└── react-dom (global)
```
## 2. browser.d.ts

`make` as well as `tsc -p .` gives me:

```
error TS6053: File '/home/tobi/workspace/grid-world/lib/typings/browser.d.ts' not found.
```

I am not really sure how to resolve that.
## 3. Visual Studio Code

Is typescript-IntelliSense working for you inside this project (.ts/.tsx files)?

**Comment by phiresky** [comment]
Typings had some API incompatible changes and is now generally deprecated. I'll see if I can switch the whole thing to npm + webpack

**Comment by phiresky** [comment]
I have converted the project to use Typescript 2 @types for module resolution and webpack for building. This should solve your issue.

https://github.com/phiresky/neural-network-demo/commit/62e1bc5486f0c1611eb3a4a13721d333a70e4adb?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
